name: Test
on: push

jobs:
  Test:
    name: test and upload coverage
    env:
      NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - name: Install
        run: npm install
      - name: Coverage
        run: npm run coverage
      - name: Upload
        run: npm run codecov